// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import { context } from "$live/live.ts";
import { DecoManifest } from "$live/types.ts";
import * as $0 from "./routes/[...catchall].tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/_middleware.ts";
import * as $3 from "./routes/api/[...catchall].tsx";
import * as $4 from "./routes/index.tsx";
import * as $$0 from "./islands/AddToCartButton.tsx";
import * as $$1 from "./islands/Filters.tsx";
import * as $$2 from "./islands/HeaderButton.tsx";
import * as $$3 from "./islands/HeaderModals.tsx";
import * as $$4 from "./islands/HeaderSearchMenu.tsx";
import * as $$5 from "./islands/Logger.tsx";
import * as $$6 from "./islands/SearchControls.tsx";
import * as $$7 from "./islands/SliderJS.tsx";
import * as $$8 from "./islands/Sort.tsx";
import * as $$$0 from "./sections/BannerGrid.tsx";
import * as $$$1 from "./sections/BannerHorizontal.tsx";
import * as $$$2 from "./sections/BannerIcones.tsx";
import * as $$$3 from "./sections/BannerSectionProduct.tsx";
import * as $$$4 from "./sections/CargoGrid.tsx";
import * as $$$5 from "./sections/Carousel.tsx";
import * as $$$6 from "./sections/ContentSideBySide.tsx";
import * as $$$7 from "./sections/ContentText.tsx";
import * as $$$8 from "./sections/CookieConsent.tsx";
import * as $$$9 from "./sections/DesignSystem.story.tsx";
import * as $$$10 from "./sections/Features.tsx";
import * as $$$11 from "./sections/Footer.tsx";
import * as $$$12 from "./sections/FormAtendimento.tsx";
import * as $$$13 from "./sections/Header.tsx";
import * as $$$14 from "./sections/Highlights.tsx";
import * as $$$15 from "./sections/Posts.tsx";
import * as $$$16 from "./sections/ProductBuyTogether.tsx";
import * as $$$17 from "./sections/ProductDetails.tsx";
import * as $$$18 from "./sections/ProductGallery.tsx";
import * as $$$19 from "./sections/ProductShelf.tsx";
import * as $$$20 from "./sections/SearchControls.tsx";
import * as $$$21 from "./sections/SectionBanner.tsx";
import * as $$$22 from "./sections/ThreeGridBanners.tsx";
import * as $$$23 from "./sections/WhatsApp.tsx";
import * as $$$24 from "deco-sites/std/sections/SEO.tsx";
import * as $$$25 from "deco-sites/std/sections/SEOPDP.tsx";
import * as $$$26 from "deco-sites/std/sections/SEOPLP.tsx";
import * as $$$27 from "deco-sites/std/sections/configOCC.global.tsx";
import * as $$$28 from "deco-sites/std/sections/configShopify.global.tsx";
import * as $$$29 from "deco-sites/std/sections/configVNDA.global.tsx";
import * as $$$30 from "deco-sites/std/sections/configVTEX.global.tsx";
import * as $$$31 from "deco-sites/std/sections/configYourViews.tsx";
import * as $$$$0 from "$live/functions/EffectSelectPage.ts";
import * as $$$$1 from "$live/functions/MatchDate.ts";
import * as $$$$2 from "$live/functions/MatchEnvironment.ts";
import * as $$$$3 from "$live/functions/MatchRandom.ts";
import * as $$$$4 from "$live/functions/MatchSite.ts";
import * as $$$$5 from "$live/functions/MatchUserAgent.ts";
import * as $$$$6 from "deco-sites/std/functions/occProductDetailsPage.ts";
import * as $$$$7 from "deco-sites/std/functions/shopifyProductDetailsPage.ts";
import * as $$$$8 from "deco-sites/std/functions/shopifyProductList.ts";
import * as $$$$9 from "deco-sites/std/functions/shopifyProductListingPage.ts";
import * as $$$$10 from "deco-sites/std/functions/vndaProductDetailsPage.ts";
import * as $$$$11 from "deco-sites/std/functions/vndaProductList.ts";
import * as $$$$12 from "deco-sites/std/functions/vndaProductListingPage.ts";
import * as $$$$13 from "deco-sites/std/functions/vtexConfig.ts";
import * as $$$$14 from "deco-sites/std/functions/vtexLegacyProductDetailsPage.ts";
import * as $$$$15 from "deco-sites/std/functions/vtexLegacyProductList.ts";
import * as $$$$16 from "deco-sites/std/functions/vtexLegacyProductListingPage.ts";
import * as $$$$17 from "deco-sites/std/functions/vtexNavbar.ts";
import * as $$$$18 from "deco-sites/std/functions/vtexProductDetailsPage.ts";
import * as $$$$19 from "deco-sites/std/functions/vtexProductList.ts";
import * as $$$$20 from "deco-sites/std/functions/vtexProductListingPage.ts";
import * as $$$$21 from "deco-sites/std/functions/vtexSuggestions.ts";

const manifest: DecoManifest = {
  routes: {
    "./routes/[...catchall].tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/_middleware.ts": $2,
    "./routes/api/[...catchall].tsx": $3,
    "./routes/index.tsx": $4,
  },
  islands: {
    "./islands/AddToCartButton.tsx": $$0,
    "./islands/Filters.tsx": $$1,
    "./islands/HeaderButton.tsx": $$2,
    "./islands/HeaderModals.tsx": $$3,
    "./islands/HeaderSearchMenu.tsx": $$4,
    "./islands/Logger.tsx": $$5,
    "./islands/SearchControls.tsx": $$6,
    "./islands/SliderJS.tsx": $$7,
    "./islands/Sort.tsx": $$8,
  },
  sections: {
    "./sections/BannerGrid.tsx": $$$0,
    "./sections/BannerHorizontal.tsx": $$$1,
    "./sections/BannerIcones.tsx": $$$2,
    "./sections/BannerSectionProduct.tsx": $$$3,
    "./sections/CargoGrid.tsx": $$$4,
    "./sections/Carousel.tsx": $$$5,
    "./sections/ContentSideBySide.tsx": $$$6,
    "./sections/ContentText.tsx": $$$7,
    "./sections/CookieConsent.tsx": $$$8,
    "./sections/DesignSystem.story.tsx": $$$9,
    "./sections/Features.tsx": $$$10,
    "./sections/Footer.tsx": $$$11,
    "./sections/FormAtendimento.tsx": $$$12,
    "./sections/Header.tsx": $$$13,
    "./sections/Highlights.tsx": $$$14,
    "./sections/Posts.tsx": $$$15,
    "./sections/ProductBuyTogether.tsx": $$$16,
    "./sections/ProductDetails.tsx": $$$17,
    "./sections/ProductGallery.tsx": $$$18,
    "./sections/ProductShelf.tsx": $$$19,
    "./sections/SearchControls.tsx": $$$20,
    "./sections/SectionBanner.tsx": $$$21,
    "./sections/ThreeGridBanners.tsx": $$$22,
    "./sections/WhatsApp.tsx": $$$23,
    "deco-sites/std/sections/SEO.tsx": $$$24,
    "deco-sites/std/sections/SEOPDP.tsx": $$$25,
    "deco-sites/std/sections/SEOPLP.tsx": $$$26,
    "deco-sites/std/sections/configOCC.global.tsx": $$$27,
    "deco-sites/std/sections/configShopify.global.tsx": $$$28,
    "deco-sites/std/sections/configVNDA.global.tsx": $$$29,
    "deco-sites/std/sections/configVTEX.global.tsx": $$$30,
    "deco-sites/std/sections/configYourViews.tsx": $$$31,
  },
  functions: {
    "$live/functions/EffectSelectPage.ts": $$$$0,
    "$live/functions/MatchDate.ts": $$$$1,
    "$live/functions/MatchEnvironment.ts": $$$$2,
    "$live/functions/MatchRandom.ts": $$$$3,
    "$live/functions/MatchSite.ts": $$$$4,
    "$live/functions/MatchUserAgent.ts": $$$$5,
    "deco-sites/std/functions/occProductDetailsPage.ts": $$$$6,
    "deco-sites/std/functions/shopifyProductDetailsPage.ts": $$$$7,
    "deco-sites/std/functions/shopifyProductList.ts": $$$$8,
    "deco-sites/std/functions/shopifyProductListingPage.ts": $$$$9,
    "deco-sites/std/functions/vndaProductDetailsPage.ts": $$$$10,
    "deco-sites/std/functions/vndaProductList.ts": $$$$11,
    "deco-sites/std/functions/vndaProductListingPage.ts": $$$$12,
    "deco-sites/std/functions/vtexConfig.ts": $$$$13,
    "deco-sites/std/functions/vtexLegacyProductDetailsPage.ts": $$$$14,
    "deco-sites/std/functions/vtexLegacyProductList.ts": $$$$15,
    "deco-sites/std/functions/vtexLegacyProductListingPage.ts": $$$$16,
    "deco-sites/std/functions/vtexNavbar.ts": $$$$17,
    "deco-sites/std/functions/vtexProductDetailsPage.ts": $$$$18,
    "deco-sites/std/functions/vtexProductList.ts": $$$$19,
    "deco-sites/std/functions/vtexProductListingPage.ts": $$$$20,
    "deco-sites/std/functions/vtexSuggestions.ts": $$$$21,
  },
  schemas: {
    "./sections/BannerGrid.tsx": {
      "inputSchema": {
        "title": " Banner Grid",
        "type": "object",
        "properties": {
          "title": {
            "type": [
              "string",
              "null",
            ],
            "title": "Title",
          },
          "itemsPerLine": {
            "title": "Items Per Line",
            "type": "object",
            "properties": {
              "mobile": {
                "type": [
                  "number",
                  "null",
                ],
                "title": "Mobile",
              },
              "desktop": {
                "type": [
                  "number",
                  "null",
                ],
                "title": "Desktop",
              },
            },
            "required": [],
            "description": "Default is 2 for mobile and all for desktop",
          },
          "borderRadius": {
            "title": "Border Radius",
            "type": "object",
            "properties": {
              "mobile": {
                "type": [
                  "number",
                  "null",
                ],
                "title": "Mobile",
              },
              "desktop": {
                "type": [
                  "number",
                  "null",
                ],
                "title": "Desktop",
              },
            },
            "required": [],
            "description": "Item's border radius in px",
          },
          "banners": {
            "type": "array",
            "items": {
              "title": "Banner",
              "type": "object",
              "properties": {
                "srcMobile": {
                  "format": "image-uri",
                  "type": "string",
                  "title": "Src Mobile",
                },
                "srcDesktop": {
                  "format": "image-uri",
                  "type": "string",
                  "title": "Src Desktop",
                },
                "alt": {
                  "type": "string",
                  "title": "Alt",
                  "description": "Image alt text",
                },
                "href": {
                  "type": "string",
                  "title": "Href",
                  "description": "When you click you go to",
                },
              },
              "required": [
                "srcMobile",
                "alt",
                "href",
              ],
            },
            "title": "Banners",
          },
        },
        "required": [
          "itemsPerLine",
          "borderRadius",
          "banners",
        ],
      },
      "outputSchema": null,
    },
    "./sections/BannerHorizontal.tsx": {
      "inputSchema": {
        "title": " Banner Horizontal",
        "type": "object",
        "properties": {
          "desktop": {
            "format": "image-uri",
            "type": "string",
            "title": "Desktop",
            "description": "desktop otimized image",
          },
          "mobile": {
            "format": "image-uri",
            "type": "string",
            "title": "Mobile",
            "description": "mobile otimized image",
          },
          "alt": {
            "type": "string",
            "title": "Alt",
            "description": "Image's alt text",
          },
          "href": {
            "type": "string",
            "title": "Href",
            "description": "when user clicks on the image, go to this link",
          },
          "title": {
            "type": "string",
            "title": "Title",
            "description": "Image text title",
          },
        },
        "required": [
          "desktop",
          "mobile",
          "alt",
          "href",
          "title",
        ],
      },
      "outputSchema": null,
    },
    "./sections/BannerIcones.tsx": {
      "inputSchema": {
        "title": " Banner Icones",
        "type": "object",
        "properties": {
          "bannerIcons": {
            "type": "array",
            "items": {
              "title": "BannerIcon",
              "type": "object",
              "properties": {
                "src": {
                  "format": "image-uri",
                  "type": "string",
                  "title": "Src",
                },
                "alt": {
                  "type": "string",
                  "title": "Alt",
                },
                "title": {
                  "type": "string",
                  "title": "Title",
                },
                "description": {
                  "type": "string",
                  "title": "Description",
                },
              },
              "required": [
                "src",
                "alt",
                "title",
                "description",
              ],
            },
            "title": "Banner Icons",
          },
        },
        "required": [
          "bannerIcons",
        ],
      },
      "outputSchema": null,
    },
    "./sections/BannerSectionProduct.tsx": {
      "inputSchema": {
        "title": " Banner Section Product",
        "type": "object",
        "properties": {
          "upperTitle": {
            "type": "string",
            "title": "Upper Title",
          },
          "title": {
            "type": "string",
            "title": "Title",
          },
          "description": {
            "type": "string",
            "title": "Description",
          },
          "desktop": {
            "format": "image-uri",
            "type": "string",
            "title": "Desktop",
            "description": "desktop otimized image",
          },
          "mobile": {
            "format": "image-uri",
            "type": "string",
            "title": "Mobile",
            "description": "mobile otimized image",
          },
          "alt": {
            "type": "string",
            "title": "Alt",
            "description": "Image's alt text",
          },
        },
        "required": [
          "upperTitle",
          "title",
          "description",
          "desktop",
          "mobile",
          "alt",
        ],
      },
      "outputSchema": null,
    },
    "./sections/CargoGrid.tsx": {
      "inputSchema": {
        "title": " Cargo Grid",
        "type": "object",
        "properties": {
          "items": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "desktop": {
                  "format": "image-uri",
                  "type": "string",
                  "title": "Desktop",
                },
                "mobile": {
                  "format": "image-uri",
                  "type": "string",
                  "title": "Mobile",
                },
                "alt": {
                  "type": "string",
                  "title": "Alt",
                },
                "titleItem": {
                  "type": "string",
                  "title": "Title Item",
                },
                "subtitleItem": {
                  "type": "string",
                  "title": "Subtitle Item",
                },
                "description": {
                  "type": "string",
                  "title": "Description",
                },
              },
              "required": [
                "mobile",
                "alt",
                "titleItem",
                "subtitleItem",
                "description",
              ],
            },
            "title": "Items",
          },
        },
        "required": [
          "items",
        ],
      },
      "outputSchema": null,
    },
    "./sections/Carousel.tsx": {
      "inputSchema": {
        "title": " Carousel",
        "type": "object",
        "properties": {
          "images": {
            "type": "array",
            "items": {
              "title": "Banner",
              "type": "object",
              "properties": {
                "desktop": {
                  "format": "image-uri",
                  "type": "string",
                  "title": "Desktop",
                  "description": "desktop otimized image",
                },
                "mobile": {
                  "format": "image-uri",
                  "type": "string",
                  "title": "Mobile",
                  "description": "mobile otimized image",
                },
                "alt": {
                  "type": "string",
                  "title": "Alt",
                  "description": "Image's alt text",
                },
                "action": {
                  "title": "Action",
                  "type": "object",
                  "properties": {
                    "href": {
                      "type": "string",
                      "title": "Href",
                    },
                    "title": {
                      "type": "string",
                      "title": "Title",
                    },
                    "subTitle": {
                      "type": "string",
                      "title": "Sub Title",
                    },
                    "label": {
                      "type": [
                        "string",
                        "null",
                      ],
                      "title": "Label",
                    },
                  },
                  "required": [
                    "href",
                    "title",
                    "subTitle",
                  ],
                },
              },
              "required": [
                "desktop",
                "mobile",
                "alt",
              ],
            },
            "title": "Images",
          },
          "preload": {
            "type": [
              "boolean",
              "null",
            ],
            "title": "Preload",
            "description":
              "Check this option when this banner is the biggest image on the screen for image optimizations",
          },
          "interval": {
            "type": [
              "number",
              "null",
            ],
            "title": "Autoplay interval",
            "description": "time (in seconds) to start the carousel autoplay",
          },
        },
        "required": [],
      },
      "outputSchema": null,
    },
    "./sections/ContentSideBySide.tsx": {
      "inputSchema": {
        "title": " Content Side By Side",
        "type": "object",
        "properties": {
          "upperTitle": {
            "type": "string",
            "title": "Upper Title",
          },
          "title": {
            "type": "string",
            "title": "Title",
          },
          "description": {
            "type": "string",
            "title": "Description",
          },
          "desktop": {
            "format": "image-uri",
            "type": "string",
            "title": "Desktop",
            "description": "desktop otimized image",
          },
          "mobile": {
            "format": "image-uri",
            "type": "string",
            "title": "Mobile",
            "description": "mobile otimized image",
          },
          "alt": {
            "type": "string",
            "title": "Alt",
            "description": "Image's alt text",
          },
        },
        "required": [
          "upperTitle",
          "title",
          "description",
          "desktop",
          "mobile",
          "alt",
        ],
      },
      "outputSchema": null,
    },
    "./sections/ContentText.tsx": {
      "inputSchema": {
        "title": " Content Text",
        "type": "object",
        "properties": {
          "title": {
            "type": [
              "string",
              "null",
            ],
            "title": "Title",
          },
          "content": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "paragraph": {
                  "type": "string",
                  "title": "Paragraph",
                },
                "divider": {
                  "type": [
                    "boolean",
                    "null",
                  ],
                  "title": "Divider",
                },
              },
              "required": [
                "paragraph",
              ],
            },
            "title": "Content",
          },
          "alignTitle": {
            "type": "string",
            "anyOf": [
              {
                "type": "string",
                "const": "center",
              },
              {
                "type": "string",
                "const": "left",
              },
            ],
            "title": "Align Title",
          },
          "modeWidth": {
            "type": "string",
            "anyOf": [
              {
                "type": "string",
                "const": "medium",
              },
              {
                "type": "string",
                "const": "large",
              },
            ],
            "title": "Mode Width",
          },
        },
        "required": [
          "content",
        ],
      },
      "outputSchema": null,
    },
    "./sections/CookieConsent.tsx": {
      "inputSchema": null,
      "outputSchema": null,
    },
    "./sections/DesignSystem.story.tsx": {
      "inputSchema": null,
      "outputSchema": null,
    },
    "./sections/Features.tsx": {
      "inputSchema": {
        "title": " Features",
        "type": "object",
        "properties": {
          "features": {
            "type": "array",
            "items": {
              "title": "Feature",
              "type": "object",
              "properties": {
                "icon": {
                  "type": "string",
                  "anyOf": [
                    {
                      "type": "string",
                      "const": "ChevronLeft",
                    },
                    {
                      "type": "string",
                      "const": "ChevronRight",
                    },
                    {
                      "type": "string",
                      "const": "ChevronUp",
                    },
                    {
                      "type": "string",
                      "const": "ChevronDown",
                    },
                    {
                      "type": "string",
                      "const": "QuestionMarkCircle",
                    },
                    {
                      "type": "string",
                      "const": "User",
                    },
                    {
                      "type": "string",
                      "const": "ShoppingCart",
                    },
                    {
                      "type": "string",
                      "const": "Bars3",
                    },
                    {
                      "type": "string",
                      "const": "Heart",
                    },
                    {
                      "type": "string",
                      "const": "MagnifyingGlass",
                    },
                    {
                      "type": "string",
                      "const": "XMark",
                    },
                    {
                      "type": "string",
                      "const": "Plus",
                    },
                    {
                      "type": "string",
                      "const": "Minus",
                    },
                    {
                      "type": "string",
                      "const": "MapPin",
                    },
                    {
                      "type": "string",
                      "const": "Phone",
                    },
                    {
                      "type": "string",
                      "const": "Elo",
                    },
                    {
                      "type": "string",
                      "const": "Mastercard",
                    },
                    {
                      "type": "string",
                      "const": "Visa",
                    },
                    {
                      "type": "string",
                      "const": "Pix",
                    },
                    {
                      "type": "string",
                      "const": "Logo",
                    },
                    {
                      "type": "string",
                      "const": "Facebook",
                    },
                    {
                      "type": "string",
                      "const": "Instagram",
                    },
                    {
                      "type": "string",
                      "const": "Tiktok",
                    },
                    {
                      "type": "string",
                      "const": "Truck",
                    },
                    {
                      "type": "string",
                      "const": "Discount",
                    },
                    {
                      "type": "string",
                      "const": "Return",
                    },
                    {
                      "type": "string",
                      "const": "CreditCard",
                    },
                    {
                      "type": "string",
                      "const": "Deco",
                    },
                    {
                      "type": "string",
                      "const": "Discord",
                    },
                    {
                      "type": "string",
                      "const": "Trash",
                    },
                    {
                      "type": "string",
                      "const": "FilterList",
                    },
                    {
                      "type": "string",
                      "const": "WhatsApp",
                    },
                    {
                      "type": "string",
                      "const": "LogoTemplateDois",
                    },
                    {
                      "type": "string",
                      "const": "icon-cart",
                    },
                    {
                      "type": "string",
                      "const": "icon-hamburger",
                    },
                    {
                      "type": "string",
                      "const": "icon-account",
                    },
                    {
                      "type": "string",
                      "const": "icon-search",
                    },
                    {
                      "type": "string",
                      "const": "icon-filter",
                    },
                    {
                      "type": "string",
                      "const": "icon-facebook",
                    },
                    {
                      "type": "string",
                      "const": "icon-whatsapp",
                    },
                    {
                      "type": "string",
                      "const": "icon-twitter",
                    },
                    {
                      "type": "string",
                      "const": "icon-next",
                    },
                    {
                      "type": "string",
                      "const": "icon-prev",
                    },
                  ],
                  "title": "Icon",
                  "description": "Image src",
                },
                "title": {
                  "type": "string",
                  "title": "Title",
                  "description": "Title",
                },
                "description": {
                  "type": "string",
                  "title": "Description",
                  "description": "Description and Image alt text",
                },
              },
              "required": [
                "icon",
                "title",
                "description",
              ],
            },
            "title": "Features",
          },
        },
        "required": [
          "features",
        ],
      },
      "outputSchema": null,
    },
    "./sections/Footer.tsx": {
      "inputSchema": {
        "title": " Footer",
        "type": "object",
        "properties": {
          "sections": {
            "type": "array",
            "items": {
              "title": "Section",
              "type": "object",
              "properties": {
                "label": {
                  "type": "string",
                  "title": "Label",
                },
                "children": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "anyOf": [
                      {
                        "title": "StringItem",
                        "type": "object",
                        "properties": {
                          "label": {
                            "type": "string",
                            "title": "Label",
                          },
                          "href": {
                            "type": "string",
                            "title": "Href",
                          },
                        },
                        "required": [
                          "label",
                          "href",
                        ],
                      },
                      {
                        "title": "IconItem",
                        "type": "object",
                        "properties": {
                          "icon": {
                            "type": "string",
                            "anyOf": [
                              {
                                "type": "string",
                                "const": "ChevronLeft",
                              },
                              {
                                "type": "string",
                                "const": "ChevronRight",
                              },
                              {
                                "type": "string",
                                "const": "ChevronUp",
                              },
                              {
                                "type": "string",
                                "const": "ChevronDown",
                              },
                              {
                                "type": "string",
                                "const": "QuestionMarkCircle",
                              },
                              {
                                "type": "string",
                                "const": "User",
                              },
                              {
                                "type": "string",
                                "const": "ShoppingCart",
                              },
                              {
                                "type": "string",
                                "const": "Bars3",
                              },
                              {
                                "type": "string",
                                "const": "Heart",
                              },
                              {
                                "type": "string",
                                "const": "MagnifyingGlass",
                              },
                              {
                                "type": "string",
                                "const": "XMark",
                              },
                              {
                                "type": "string",
                                "const": "Plus",
                              },
                              {
                                "type": "string",
                                "const": "Minus",
                              },
                              {
                                "type": "string",
                                "const": "MapPin",
                              },
                              {
                                "type": "string",
                                "const": "Phone",
                              },
                              {
                                "type": "string",
                                "const": "Elo",
                              },
                              {
                                "type": "string",
                                "const": "Mastercard",
                              },
                              {
                                "type": "string",
                                "const": "Visa",
                              },
                              {
                                "type": "string",
                                "const": "Pix",
                              },
                              {
                                "type": "string",
                                "const": "Logo",
                              },
                              {
                                "type": "string",
                                "const": "Facebook",
                              },
                              {
                                "type": "string",
                                "const": "Instagram",
                              },
                              {
                                "type": "string",
                                "const": "Tiktok",
                              },
                              {
                                "type": "string",
                                "const": "Truck",
                              },
                              {
                                "type": "string",
                                "const": "Discount",
                              },
                              {
                                "type": "string",
                                "const": "Return",
                              },
                              {
                                "type": "string",
                                "const": "CreditCard",
                              },
                              {
                                "type": "string",
                                "const": "Deco",
                              },
                              {
                                "type": "string",
                                "const": "Discord",
                              },
                              {
                                "type": "string",
                                "const": "Trash",
                              },
                              {
                                "type": "string",
                                "const": "FilterList",
                              },
                              {
                                "type": "string",
                                "const": "WhatsApp",
                              },
                              {
                                "type": "string",
                                "const": "LogoTemplateDois",
                              },
                              {
                                "type": "string",
                                "const": "icon-cart",
                              },
                              {
                                "type": "string",
                                "const": "icon-hamburger",
                              },
                              {
                                "type": "string",
                                "const": "icon-account",
                              },
                              {
                                "type": "string",
                                "const": "icon-search",
                              },
                              {
                                "type": "string",
                                "const": "icon-filter",
                              },
                              {
                                "type": "string",
                                "const": "icon-facebook",
                              },
                              {
                                "type": "string",
                                "const": "icon-whatsapp",
                              },
                              {
                                "type": "string",
                                "const": "icon-twitter",
                              },
                              {
                                "type": "string",
                                "const": "icon-next",
                              },
                              {
                                "type": "string",
                                "const": "icon-prev",
                              },
                            ],
                            "title": "Icon",
                          },
                        },
                        "required": [
                          "icon",
                        ],
                      },
                    ],
                    "title": "Item",
                  },
                  "title": "Children",
                },
              },
              "required": [
                "label",
                "children",
              ],
            },
            "title": "Sections",
          },
        },
        "required": [],
      },
      "outputSchema": null,
    },
    "./sections/FormAtendimento.tsx": {
      "inputSchema": null,
      "outputSchema": null,
    },
    "./sections/Header.tsx": {
      "inputSchema": {
        "title": " Header",
        "type": "object",
        "properties": {
          "alerts": {
            "type": "array",
            "items": {
              "type": "string",
            },
            "title": "Alerts",
          },
          "searchbar": {
            "title": "Search Bar",
            "type": "object",
            "properties": {
              "placeholder": {
                "type": [
                  "string",
                  "null",
                ],
                "title": "Placeholder",
                "description": "Search bar default placeholder message",
                "default": "What are you looking for?",
              },
              "action": {
                "type": [
                  "string",
                  "null",
                ],
                "title": "Page path",
                "description":
                  "When user clicks on the search button, navigate it to",
                "default": "/s",
              },
              "name": {
                "type": [
                  "string",
                  "null",
                ],
                "title": "Term name",
                "description":
                  "Querystring param used when navigating the user",
                "default": "q",
              },
              "query": {
                "type": [
                  "string",
                  "null",
                ],
                "title": "Query",
              },
            },
            "required": [],
          },
          "navItems": {
            "type": "array",
            "items": {
              "title": "NavItem",
              "type": "object",
              "properties": {
                "label": {
                  "type": "string",
                  "title": "Label",
                },
                "href": {
                  "type": "string",
                  "title": "Href",
                },
                "children": {
                  "title": "Children",
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "label": {
                        "type": "string",
                        "title": "Label",
                      },
                      "href": {
                        "type": "string",
                        "title": "Href",
                      },
                      "children": {
                        "title": "Children",
                        "type": "array",
                        "items": {
                          "type": "object",
                          "properties": {
                            "label": {
                              "type": "string",
                              "title": "Label",
                            },
                            "href": {
                              "type": "string",
                              "title": "Href",
                            },
                          },
                          "required": [
                            "label",
                            "href",
                          ],
                        },
                      },
                    },
                    "required": [
                      "label",
                      "href",
                    ],
                  },
                },
                "image": {
                  "title": "Image",
                  "type": "object",
                  "properties": {
                    "src": {
                      "format": "image-uri",
                      "type": "string",
                      "title": "Src",
                    },
                    "alt": {
                      "type": [
                        "string",
                        "null",
                      ],
                      "title": "Alt",
                    },
                  },
                  "required": [],
                },
              },
              "required": [
                "label",
                "href",
              ],
            },
            "title": "Navigation items",
            "description":
              "Navigation items used both on mobile and desktop menus",
          },
          "products": {
            "$id": "bae848f3957be1cb6ed2c2ac3847787272389ee9",
            "format": "live-function",
            "type": "string",
            "title": "Product suggestions",
            "description": "Product suggestions displayed on search",
          },
          "suggestions": {
            "$id": "fa622ecbfb24e1b878a945d22f51f46a3e939525",
            "format": "live-function",
            "type": "string",
            "title": "Enable Top Search terms",
          },
          "configVTEX": {
            "$id": "4a94f4ff0e8e4441f26651aaed22f0df82f38c93",
            "format": "live-function",
            "type": "string",
            "title": "Config V T E X",
            "description": "vtex config used for search autocompletion;",
          },
        },
        "required": [
          "alerts",
        ],
      },
      "outputSchema": null,
    },
    "./sections/Highlights.tsx": {
      "inputSchema": {
        "title": " Highlights",
        "type": "object",
        "properties": {
          "highlights": {
            "type": "array",
            "items": {
              "title": "Highlight",
              "type": "object",
              "properties": {
                "src": {
                  "format": "image-uri",
                  "type": "string",
                  "title": "Src",
                },
                "alt": {
                  "type": "string",
                  "title": "Alt",
                },
                "href": {
                  "type": "string",
                  "title": "Href",
                },
                "label": {
                  "type": "string",
                  "title": "Label",
                },
              },
              "required": [
                "src",
                "alt",
                "href",
                "label",
              ],
            },
            "title": "Highlights",
          },
          "title": {
            "type": "string",
            "title": "Title",
          },
        },
        "required": [
          "title",
        ],
      },
      "outputSchema": null,
    },
    "./sections/Posts.tsx": {
      "inputSchema": {
        "title": " Posts",
        "type": "object",
        "properties": {
          "titleSession": {
            "type": "string",
            "title": "Title Session",
          },
          "posts": {
            "type": "array",
            "items": {
              "title": "Post",
              "type": "object",
              "properties": {
                "title": {
                  "type": "string",
                  "title": "Title",
                },
                "description": {
                  "type": "string",
                  "title": "Description",
                },
                "alt": {
                  "type": "string",
                  "title": "Alt",
                },
                "href": {
                  "type": "string",
                  "title": "Href",
                },
                "src": {
                  "format": "image-uri",
                  "type": "string",
                  "title": "Src",
                },
              },
              "required": [
                "title",
                "description",
                "alt",
                "href",
                "src",
              ],
            },
            "title": "Posts",
          },
        },
        "required": [
          "titleSession",
          "posts",
        ],
      },
      "outputSchema": null,
    },
    "./sections/ProductBuyTogether.tsx": {
      "inputSchema": {
        "title": " Product Buy Together",
        "type": "object",
        "properties": {
          "title": {
            "type": "string",
            "title": "Title",
          },
          "products": {
            "$id": "bae848f3957be1cb6ed2c2ac3847787272389ee9",
            "format": "live-function",
            "type": "string",
            "title": "Products",
          },
          "itemsPerPage": {
            "type": [
              "number",
              "null",
            ],
            "title": "Items Per Page",
          },
        },
        "required": [
          "title",
          "products",
        ],
      },
      "outputSchema": null,
    },
    "./sections/ProductDetails.tsx": {
      "inputSchema": {
        "title": " Product Details",
        "type": "object",
        "properties": {
          "page": {
            "$id": "bf6c5311c35f44b8ba333ce3c2acd5fed0d8ad8a",
            "format": "live-function",
            "type": "string",
            "title": "Page",
          },
        },
        "required": [
          "page",
        ],
      },
      "outputSchema": null,
    },
    "./sections/ProductGallery.tsx": {
      "inputSchema": {
        "title": " Product Gallery",
        "type": "object",
        "properties": {
          "page": {
            "$id": "93678a2f6c9ab06d039c9fcd9714055f1a81449f",
            "format": "live-function",
            "type": "string",
            "title": "Page",
          },
        },
        "required": [
          "page",
        ],
      },
      "outputSchema": null,
    },
    "./sections/ProductShelf.tsx": {
      "inputSchema": {
        "title": " Product Shelf",
        "type": "object",
        "properties": {
          "title": {
            "type": "string",
            "title": "Title",
          },
          "products": {
            "$id": "bae848f3957be1cb6ed2c2ac3847787272389ee9",
            "format": "live-function",
            "type": "string",
            "title": "Products",
          },
          "itemsPerPage": {
            "type": [
              "number",
              "null",
            ],
            "title": "Items Per Page",
          },
        },
        "required": [
          "title",
          "products",
        ],
      },
      "outputSchema": null,
    },
    "./sections/SearchControls.tsx": {
      "inputSchema": {
        "title": " Search Controls",
        "type": "object",
        "properties": {
          "page": {
            "$id": "93678a2f6c9ab06d039c9fcd9714055f1a81449f",
            "format": "live-function",
            "type": "string",
            "title": "Page",
          },
        },
        "required": [
          "page",
        ],
      },
      "outputSchema": null,
    },
    "./sections/SectionBanner.tsx": {
      "inputSchema": {
        "title": " Section Banner",
        "type": "object",
        "properties": {
          "desktop": {
            "title": "Desktop",
            "type": "object",
            "properties": {
              "src": {
                "format": "image-uri",
                "type": "string",
                "title": "Src",
              },
              "width": {
                "type": [
                  "number",
                  "null",
                ],
                "title": "Width",
              },
              "height": {
                "type": [
                  "number",
                  "null",
                ],
                "title": "Height",
              },
            },
            "required": [
              "src",
            ],
            "description": "desktop otimized image",
          },
          "mobile": {
            "title": "Mobile",
            "type": "object",
            "properties": {
              "src": {
                "format": "image-uri",
                "type": "string",
                "title": "Src",
              },
              "width": {
                "type": [
                  "number",
                  "null",
                ],
                "title": "Width",
              },
              "height": {
                "type": [
                  "number",
                  "null",
                ],
                "title": "Height",
              },
            },
            "required": [
              "src",
            ],
            "description": "mobile otimized image",
          },
          "alt": {
            "type": "string",
            "title": "Alt",
            "description": "Image's alt text",
          },
          "upperTitle": {
            "type": "string",
            "title": "Upper Title",
          },
          "title": {
            "type": "string",
            "title": "Title",
          },
          "description": {
            "type": "string",
            "title": "Description",
          },
          "preload": {
            "type": [
              "boolean",
              "null",
            ],
            "title": "Preload",
          },
          "aspectRatio": {
            "type": [
              "string",
              "null",
            ],
            "title": "Aspect Ratio",
          },
        },
        "required": [
          "desktop",
          "mobile",
          "alt",
          "upperTitle",
          "title",
          "description",
        ],
      },
      "outputSchema": null,
    },
    "./sections/ThreeGridBanners.tsx": {
      "inputSchema": {
        "title": " Three Grid Banners",
        "type": "object",
        "properties": {
          "gridBanners": {
            "type": "array",
            "items": {
              "title": "GridBanner",
              "type": "object",
              "properties": {
                "desktop": {
                  "format": "image-uri",
                  "type": "string",
                  "title": "Desktop",
                  "description": "desktop otimized image",
                },
                "mobile": {
                  "format": "image-uri",
                  "type": "string",
                  "title": "Mobile",
                  "description": "mobile otimized image",
                },
                "alt": {
                  "type": "string",
                  "title": "Alt",
                  "description": "Image's alt text",
                },
                "action": {
                  "title": "Action",
                  "type": "object",
                  "properties": {
                    "href": {
                      "type": "string",
                      "title": "Href",
                    },
                    "description": {
                      "type": "string",
                      "title": "Description",
                    },
                    "label": {
                      "type": [
                        "string",
                        "null",
                      ],
                      "title": "Label",
                    },
                  },
                  "required": [
                    "href",
                    "description",
                  ],
                },
              },
              "required": [
                "desktop",
                "mobile",
                "alt",
                "action",
              ],
            },
            "title": "Grid Banners",
          },
        },
        "required": [
          "gridBanners",
        ],
      },
      "outputSchema": null,
    },
    "./sections/WhatsApp.tsx": {
      "inputSchema": {
        "title": " Whats App",
        "type": "object",
        "properties": {
          "phone": {
            "type": [
              "number",
              "null",
            ],
            "title": "Phone",
          },
        },
        "required": [],
      },
      "outputSchema": null,
    },
    "$live/functions/EffectSelectPage.ts": {
      "inputSchema": {
        "title": " Effect Select Page",
        "type": "object",
        "properties": {
          "pageIds": {
            "type": "array",
            "items": {
              "type": "number",
            },
            "title": "Page Ids",
          },
        },
        "required": [
          "pageIds",
        ],
      },
      "outputSchema": null,
    },
    "$live/functions/MatchDate.ts": {
      "inputSchema": {
        "title": " Match Date",
        "type": "object",
        "properties": {
          "start": {
            "type": [
              "string",
              "null",
            ],
            "title": "Start",
            "format": "date-time",
          },
          "end": {
            "type": [
              "string",
              "null",
            ],
            "title": "End",
            "format": "date-time",
          },
          "session": {
            "type": "boolean",
            "title": "Session",
          },
        },
        "required": [
          "session",
        ],
      },
      "outputSchema": null,
    },
    "$live/functions/MatchEnvironment.ts": {
      "inputSchema": {
        "title": " Match Environment",
        "type": "object",
        "properties": {
          "environment": {
            "type": "string",
            "anyOf": [
              {
                "type": "string",
                "const": "production",
              },
              {
                "type": "string",
                "const": "development",
              },
            ],
            "title": "Environment",
          },
        },
        "required": [
          "environment",
        ],
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "c995d72dc372b1b50bf9f70943e37fc94e1ccac9",
          },
        },
        "additionalProperties": true,
      },
    },
    "$live/functions/MatchRandom.ts": {
      "inputSchema": {
        "title": " Match Random",
        "type": "object",
        "properties": {
          "traffic": {
            "type": "number",
            "title": "Traffic",
          },
          "session": {
            "type": "boolean",
            "title": "Session",
          },
        },
        "required": [
          "traffic",
          "session",
        ],
      },
      "outputSchema": null,
    },
    "$live/functions/MatchSite.ts": {
      "inputSchema": {
        "title": " Match Site",
        "type": "object",
        "properties": {
          "siteId": {
            "type": "number",
            "title": "Site Id",
          },
        },
        "required": [
          "siteId",
        ],
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "c995d72dc372b1b50bf9f70943e37fc94e1ccac9",
          },
        },
        "additionalProperties": true,
      },
    },
    "$live/functions/MatchUserAgent.ts": {
      "inputSchema": {
        "title": " Match User Agent",
        "type": "object",
        "properties": {
          "includes": {
            "type": [
              "string",
              "null",
            ],
            "title": "Includes",
          },
          "match": {
            "type": [
              "string",
              "null",
            ],
            "title": "Match",
          },
        },
        "required": [],
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "c995d72dc372b1b50bf9f70943e37fc94e1ccac9",
          },
        },
        "additionalProperties": true,
      },
    },
    "deco-sites/std/sections/SEO.tsx": {
      "inputSchema": {
        "title": " S E O",
        "type": "object",
        "properties": {
          "title": {
            "type": [
              "string",
              "null",
            ],
            "title": "Title",
          },
          "description": {
            "type": [
              "string",
              "null",
            ],
            "title": "Description",
          },
          "url": {
            "type": [
              "string",
              "null",
            ],
            "title": "Url",
          },
          "imageUrl": {
            "type": [
              "string",
              "null",
            ],
            "title": "Image Url",
          },
          "themeColor": {
            "type": [
              "string",
              "null",
            ],
            "title": "Theme Color",
          },
        },
        "required": [],
      },
      "outputSchema": null,
    },
    "deco-sites/std/sections/SEOPDP.tsx": {
      "inputSchema": {
        "title": " S E O P D P",
        "type": "object",
        "properties": {
          "page": {
            "$id": "bf6c5311c35f44b8ba333ce3c2acd5fed0d8ad8a",
            "format": "live-function",
            "type": "string",
            "title": "Page",
          },
          "titleTemplate": {
            "type": "string",
            "title": "Title template",
            "description":
              "add a %s whenever you want it to be replaced with the product name",
            "default": "%s | Fashion Store",
          },
          "description": {
            "type": [
              "string",
              "null",
            ],
            "title": "Meta tag description",
            "description":
              "If not set, the product description will be used instead",
          },
          "themeColor": {
            "type": [
              "string",
              "null",
            ],
            "title": "Theme Color",
          },
        },
        "required": [
          "page",
          "titleTemplate",
        ],
      },
      "outputSchema": null,
    },
    "deco-sites/std/sections/SEOPLP.tsx": {
      "inputSchema": {
        "title": " S E O P L P",
        "type": "object",
        "properties": {
          "page": {
            "$id": "93678a2f6c9ab06d039c9fcd9714055f1a81449f",
            "format": "live-function",
            "type": "string",
            "title": "Page",
          },
          "title": {
            "type": [
              "string",
              "null",
            ],
            "title": "Title",
          },
          "description": {
            "type": [
              "string",
              "null",
            ],
            "title": "Description",
          },
          "url": {
            "type": [
              "string",
              "null",
            ],
            "title": "Url",
          },
          "imageUrl": {
            "type": [
              "string",
              "null",
            ],
            "title": "Image Url",
          },
          "themeColor": {
            "type": [
              "string",
              "null",
            ],
            "title": "Theme Color",
          },
        },
        "required": [
          "page",
        ],
      },
      "outputSchema": null,
    },
    "deco-sites/std/sections/configOCC.global.tsx": {
      "inputSchema": {
        "title": "Config O C C.global",
        "type": "object",
        "properties": {
          "baseUrl": {
            "type": "string",
            "title": "Base Url",
          },
          "nrpp": {
            "type": [
              "string",
              "null",
            ],
            "title": "Nrpp",
          },
        },
        "required": [
          "baseUrl",
        ],
      },
      "outputSchema": null,
    },
    "deco-sites/std/sections/configShopify.global.tsx": {
      "inputSchema": {
        "title": "Config Shopify.global",
        "type": "object",
        "properties": {
          "storeName": {
            "type": "string",
            "title": "Store Name",
            "description": "Shopify store name.",
          },
          "storefrontAccessToken": {
            "type": "string",
            "title": "Storefront Access Token",
            "description": "Shopify storefront access token.",
          },
        },
        "required": [
          "storeName",
          "storefrontAccessToken",
        ],
      },
      "outputSchema": null,
    },
    "deco-sites/std/sections/configVNDA.global.tsx": {
      "inputSchema": {
        "title": "Config V N D A.global",
        "type": "object",
        "properties": {
          "domain": {
            "type": "string",
            "title": "Domain",
            "description":
              "Your VNDA domain name. For example, https://mystore.vnda.com.br",
          },
          "authToken": {
            "type": "string",
            "title": "Auth Token",
            "description":
              "The token generated from admin panel. Read here: https://developers.vnda.com.br/docs/chave-de-acesso-e-requisicoes",
          },
          "useSandbox": {
            "type": "boolean",
            "title": "Use Sandbox",
            "description": "Define if sandbox environment should be used",
          },
          "defaultPriceCurrency": {
            "type": "string",
            "title": "Default Price Currency",
            "description": "Default price currency.",
            "default": "USD",
          },
        },
        "required": [
          "domain",
          "authToken",
          "useSandbox",
          "defaultPriceCurrency",
        ],
      },
      "outputSchema": null,
    },
    "deco-sites/std/sections/configVTEX.global.tsx": {
      "inputSchema": {
        "title": "Config V T E X.global",
        "type": "object",
        "properties": {
          "account": {
            "type": "string",
            "title": "Account",
            "description":
              "VTEX Account name. For more info, read here: https://help.vtex.com/en/tutorial/o-que-e-account-name--i0mIGLcg3QyEy8OCicEoC.",
          },
          "defaultLocale": {
            "type": "string",
            "title": "Default Locale",
            "description": "Locale used for VTEX Intelligent Search client.",
          },
          "defaultPriceCurrency": {
            "type": "string",
            "title": "Default Price Currency",
            "description": "Default price currency.",
            "default": "USD",
          },
          "defaultSalesChannel": {
            "type": "string",
            "title": "Default Sales Channel",
            "description":
              "VTEX sales channel. This will be the default sales channel your site. For more info, read here: https://help.vtex.com/tutorial/how-trade-policies-work--6Xef8PZiFm40kg2STrMkMV",
          },
          "defaultRegionId": {
            "type": [
              "string",
              "null",
            ],
            "title": "Default Region Id",
          },
          "defaultHideUnnavailableItems": {
            "type": [
              "boolean",
              "null",
            ],
            "title": "Default Hide Unnavailable Items",
          },
        },
        "required": [
          "account",
          "defaultLocale",
          "defaultPriceCurrency",
          "defaultSalesChannel",
        ],
      },
      "outputSchema": null,
    },
    "deco-sites/std/sections/configYourViews.tsx": {
      "inputSchema": {
        "title": "Config Your Views",
        "type": "object",
        "properties": {
          "token": {
            "type": "string",
            "title": "Token",
          },
          "appId": {
            "type": "string",
            "title": "App Id",
          },
        },
        "required": [
          "token",
          "appId",
        ],
      },
      "outputSchema": null,
    },
    "deco-sites/std/functions/occProductDetailsPage.ts": {
      "inputSchema": {
        "type": "null",
        "title": "Occ Product Details Page",
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "bf6c5311c35f44b8ba333ce3c2acd5fed0d8ad8a",
          },
        },
        "additionalProperties": true,
      },
    },
    "deco-sites/std/functions/shopifyProductDetailsPage.ts": {
      "inputSchema": {
        "type": "null",
        "title": "Shopify Product Details Page",
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "bf6c5311c35f44b8ba333ce3c2acd5fed0d8ad8a",
          },
        },
        "additionalProperties": true,
      },
    },
    "deco-sites/std/functions/shopifyProductList.ts": {
      "inputSchema": {
        "title": "Shopify Product List",
        "type": "object",
        "properties": {
          "query": {
            "type": "string",
            "title": "Query",
            "description": "search term to use on search",
          },
          "count": {
            "type": "number",
            "title": "Count",
            "description": "total number of items to display",
          },
        },
        "required": [
          "query",
          "count",
        ],
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "bae848f3957be1cb6ed2c2ac3847787272389ee9",
          },
        },
        "additionalProperties": true,
      },
    },
    "deco-sites/std/functions/shopifyProductListingPage.ts": {
      "inputSchema": {
        "title": "Shopify Product Listing Page",
        "type": "object",
        "properties": {
          "query": {
            "type": [
              "string",
              "null",
            ],
            "title": "Query",
            "description": "overides the query term",
          },
          "count": {
            "type": "number",
            "title": "Items per page",
            "description": "number of products per page to display",
          },
        },
        "required": [
          "count",
        ],
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "93678a2f6c9ab06d039c9fcd9714055f1a81449f",
          },
        },
        "additionalProperties": true,
      },
    },
    "deco-sites/std/functions/vndaProductDetailsPage.ts": {
      "inputSchema": {
        "type": "null",
        "title": "Vnda Product Details Page",
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "bf6c5311c35f44b8ba333ce3c2acd5fed0d8ad8a",
          },
        },
        "additionalProperties": true,
      },
    },
    "deco-sites/std/functions/vndaProductList.ts": {
      "inputSchema": {
        "title": "Vnda Product List",
        "type": "object",
        "properties": {
          "limit": {
            "type": "number",
            "title": "Limit",
            "description": "total number of items to display",
          },
          "term": {
            "type": [
              "string",
              "null",
            ],
            "title": "Term",
            "description": "query to use on search",
          },
          "wildcard": {
            "type": [
              "boolean",
              "null",
            ],
            "title": "Wildcard",
            "description": "search for term anywhere",
          },
          "sort": {
            "type": "string",
            "anyOf": [
              {
                "type": "string",
                "const": "newest",
              },
              {
                "type": "string",
                "const": "oldest",
              },
              {
                "type": "string",
                "const": "lowest_price",
              },
              {
                "type": "string",
                "const": "highest_price",
              },
            ],
            "title": "Sort",
            "description": "search sort parameter",
          },
          "tags": {
            "type": "array",
            "items": {
              "type": "string",
            },
            "title": "Tags",
            "description": "search for products that have certain tag",
          },
        },
        "required": [
          "limit",
        ],
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "bae848f3957be1cb6ed2c2ac3847787272389ee9",
          },
        },
        "additionalProperties": true,
      },
    },
    "deco-sites/std/functions/vndaProductListingPage.ts": {
      "inputSchema": {
        "title": "Vnda Product Listing Page",
        "type": "object",
        "properties": {
          "term": {
            "type": [
              "string",
              "null",
            ],
            "title": "Term",
            "description": "overides the query term",
          },
          "tags": {
            "type": "array",
            "items": {
              "type": "string",
            },
            "title": "Tags",
            "description": "filter products by tag",
          },
          "count": {
            "type": "number",
            "title": "Items per page",
            "description": "number of products per page to display",
          },
        },
        "required": [
          "count",
        ],
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "93678a2f6c9ab06d039c9fcd9714055f1a81449f",
          },
        },
        "additionalProperties": true,
      },
    },
    "deco-sites/std/functions/vtexConfig.ts": {
      "inputSchema": {
        "type": "null",
        "title": "Vtex Config",
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "4a94f4ff0e8e4441f26651aaed22f0df82f38c93",
          },
        },
        "additionalProperties": true,
      },
    },
    "deco-sites/std/functions/vtexLegacyProductDetailsPage.ts": {
      "inputSchema": {
        "type": "null",
        "title": "Vtex Legacy Product Details Page",
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "bf6c5311c35f44b8ba333ce3c2acd5fed0d8ad8a",
          },
        },
        "additionalProperties": true,
      },
    },
    "deco-sites/std/functions/vtexLegacyProductList.ts": {
      "inputSchema": {
        "title": "Vtex Legacy Product List",
        "type": "object",
        "properties": {
          "query": {
            "type": "string",
            "title": "Query",
            "description": "query to use on search",
          },
          "count": {
            "type": "number",
            "title": "Count",
            "description": "total number of items to display",
          },
          "sort": {
            "type": "string",
            "anyOf": [
              {
                "type": "string",
                "const": "",
              },
              {
                "type": "string",
                "const": "price:desc",
              },
              {
                "type": "string",
                "const": "price:asc",
              },
              {
                "type": "string",
                "const": "orders:desc",
              },
              {
                "type": "string",
                "const": "name:desc",
              },
              {
                "type": "string",
                "const": "name:asc",
              },
              {
                "type": "string",
                "const": "release:desc",
              },
              {
                "type": "string",
                "const": "discount:desc",
              },
            ],
            "title": "Sort",
            "description": "search sort parameter",
          },
          "collection": {
            "type": "array",
            "items": {
              "type": "string",
            },
            "title": "Collection",
            "description":
              "Collection ID or (Product Cluster id). For more info: https://developers.vtex.com/docs/api-reference/search-api#get-/api/catalog_system/pub/products/search .",
            "pattern": "\\d*",
          },
        },
        "required": [
          "query",
          "count",
        ],
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "bae848f3957be1cb6ed2c2ac3847787272389ee9",
          },
        },
        "additionalProperties": true,
      },
    },
    "deco-sites/std/functions/vtexLegacyProductListingPage.ts": {
      "inputSchema": {
        "title": "Vtex Legacy Product Listing Page",
        "type": "object",
        "properties": {
          "term": {
            "type": [
              "string",
              "null",
            ],
            "title": "Term",
            "description": "overides the query term",
          },
          "count": {
            "type": "number",
            "title": "Items per page",
            "description": "number of products per page to display",
          },
          "ft": {
            "type": [
              "string",
              "null",
            ],
            "title": "Ft",
            "description": "FullText term",
          },
          "fq": {
            "type": [
              "string",
              "null",
            ],
            "title": "Fq",
          },
          "map": {
            "type": [
              "string",
              "null",
            ],
            "title": "Map",
            "description": "map param",
          },
        },
        "required": [
          "count",
        ],
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "93678a2f6c9ab06d039c9fcd9714055f1a81449f",
          },
        },
        "additionalProperties": true,
      },
    },
    "deco-sites/std/functions/vtexNavbar.ts": {
      "inputSchema": {
        "title": "Vtex Navbar",
        "type": "object",
        "properties": {
          "levels": {
            "type": [
              "number",
              "null",
            ],
            "title": "Levels",
            "description": "Number of levels of categories to be returned",
            "default": "2",
          },
        },
        "required": [],
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "0244534df7e3d23a94046f4c6f7086c2b72853b8",
          },
        },
        "additionalProperties": true,
      },
    },
    "deco-sites/std/functions/vtexProductDetailsPage.ts": {
      "inputSchema": {
        "type": "null",
        "title": "Vtex Product Details Page",
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "bf6c5311c35f44b8ba333ce3c2acd5fed0d8ad8a",
          },
        },
        "additionalProperties": true,
      },
    },
    "deco-sites/std/functions/vtexProductList.ts": {
      "inputSchema": {
        "title": "Vtex Product List",
        "type": "object",
        "properties": {
          "query": {
            "type": "string",
            "title": "Query",
            "description": "query to use on search",
          },
          "count": {
            "type": "number",
            "title": "Count",
            "description": "total number of items to display",
          },
          "sort": {
            "type": "string",
            "anyOf": [
              {
                "type": "string",
                "const": "",
              },
              {
                "type": "string",
                "const": "price:desc",
              },
              {
                "type": "string",
                "const": "price:asc",
              },
              {
                "type": "string",
                "const": "orders:desc",
              },
              {
                "type": "string",
                "const": "name:desc",
              },
              {
                "type": "string",
                "const": "name:asc",
              },
              {
                "type": "string",
                "const": "release:desc",
              },
              {
                "type": "string",
                "const": "discount:desc",
              },
            ],
            "title": "Sort",
            "description": "search sort parameter",
          },
          "collection": {
            "type": "array",
            "items": {
              "type": "string",
            },
            "title": "Collection",
            "description":
              "Collection ID or (Product Cluster id). For more info: https://developers.vtex.com/docs/api-reference/search-api#get-/api/catalog_system/pub/products/search .",
            "pattern": "\\d*",
          },
        },
        "required": [
          "query",
          "count",
        ],
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "bae848f3957be1cb6ed2c2ac3847787272389ee9",
          },
        },
        "additionalProperties": true,
      },
    },
    "deco-sites/std/functions/vtexProductListingPage.ts": {
      "inputSchema": {
        "title": "Vtex Product Listing Page",
        "type": "object",
        "properties": {
          "query": {
            "type": [
              "string",
              "null",
            ],
            "title": "Query",
            "description": "overides the query term",
          },
          "count": {
            "type": "number",
            "title": "Items per page",
            "description": "number of products per page to display",
          },
        },
        "required": [
          "count",
        ],
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "93678a2f6c9ab06d039c9fcd9714055f1a81449f",
          },
        },
        "additionalProperties": true,
      },
    },
    "deco-sites/std/functions/vtexSuggestions.ts": {
      "inputSchema": {
        "title": "Vtex Suggestions",
        "type": "object",
        "properties": {
          "count": {
            "type": [
              "number",
              "null",
            ],
            "title": "Count",
            "description": "limit the number of searches",
            "default": "4",
          },
        },
        "required": [],
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "fa622ecbfb24e1b878a945d22f51f46a3e939525",
          },
        },
        "additionalProperties": true,
      },
    },
  },
  baseUrl: import.meta.url,
  config,
};

// live — this exposes the manifest so the live server can render components dynamically
context.manifest = manifest;

export default manifest;
